### ISSUE TITLE
Add resources or Further Reading chapter with links to relevant reports

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#21]
Jesse suggested adding a Further Reading section. Decarb, AEA, etc.  Renewable energy

Brittany warned about dead links

Dayne suggested  subfolder with redirect or cached the thing (Dayne can show) `resouces`

- [ ] Add a new folder called `resources`
- [ ] Add a cache of report PDFs in case the originals go away
- [ ] Add redirect webpage that will use the cache if the original link goes away
- [ ] Use the redirect links in a further_reading.qmd page that will never die and never grow old

**Comment by ianalexmac** [comment]
Should we cache html webpages? I'm looking at our link to the [PCE webpage](https://www.akenergyauthority.org/What-We-Do/Power-Cost-Equalization) and wondering what to do.

**Comment by ianalexmac** [comment]
https://www.akenergyauthority.org/What-We-Do/Power-Cost-Equalization

**Comment by eldobbins** [comment]
- Idea came from discussions by researchers.  Railbelt decarb.  etc. But they didn't follow up
- fancy links?
  - Will this report outlast the links?  Not convinced it will.
- Jesse downloaded reports and size was ~600 MB.  He has them stashed locally.  Would use LFS
- ISER etc wants usage statistic so we shouldn't point to locally hosted copies by default.

Blocked by lack of direction.

**Comment by jikac** [comment]
No longer a priority.
