### ISSUE TITLE
Visualization of history of the report (and clarify language)

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#24]
Make a visualization of the historical report.  Excalidraw version?  Can that be rendered directly by Quarto?

Also, the front page refers to this web book being the descendent on the _Energy Statistics Report_. About page too.  But Dayne sees the relationship differently, so that language needs to change.

Dayne says
> the spade was to remind us to put the context that this Trends Report is complimentary to but is not a direct successor of those prior reports

- [x] Excalidraw version of timeline
- [ ] render that in Quarto?  
- [x] needs to be updated.  Dots for each report to reflect actual release dates. (Jesse will do)
- [x] Change front page re "ancestor"/"descendent"
- [x] Change About this Report page to fix language there too
- [x] copy table from draft.

**Comment by ianalexmac** [comment]
Timeline added to Google Doc. If we like what we see,  I could explore rendering in Quarto.

**Comment by eldobbins** [comment]
Copy table from draft when that is finalized

**Comment by eldobbins** [comment]
Quarto doesn't do Excalidraw.  [Quarto will render](https://quarto.org/docs/authoring/diagrams.html) Mermaid and Graphic. I don't think either of those is nice enough.

As a stop-gap, I have uploaded the PNG into `images/`and the Excalidraw script into `scripts`.  I am updating the figure at https://excalidraw.com and will upload new versions when those are ready.

**Comment by eldobbins** [comment]
@jikaczmarski can you review the updated image on https://acep-uaf.github.io/aetr-web-book-2024/about.html.  If it looks OK, please close this issue.

**Comment by jikac** [comment]
Phenomenal
