### ISSUE TITLE
Adjust plotting order to prevent empty area underneath landfill gas from 2012-13

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#25]

**Comment by ianalexmac** [comment]
@jikaczmarski I have had similar problems, so have been bulking out my margins. 
```
Plot.plot({
     marginRight: 70

```

**Comment by jikac** [comment]
@ianalexmac I should have been more specific. I mean the order of how the series are plotted. On the statewide capacity graph you'll see that landfill gas starts getting plotted in 2012, but storage doesn't start until 2013. Because Observable defaults storage before landfill gas, it creates this empty space underneath the landfill gas line from 2012-2013.

**Comment by ianalexmac** [comment]
Oh! Gotcha. Thanks.
