### ISSUE TITLE
Write an action that generates a zip file in the final data directory on push

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#31]
There is a marketplace action https://github.com/marketplace/actions/action-zip

**Comment by ianalexmac** [comment]
Zip files are also binary? Maybe it should be stored elsewhere alongside the DB.

**Comment by ianalexmac** [comment]
@dayne has requested that we NOT generate a zip file of the data directory, but instead do a tag and release which will allow zip download of entire repo.

**Comment by ianalexmac** [comment]
Closing this issue because we are going a different direction.
