### ISSUE TITLE
Add metadata for source data

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#33]
- [x] Net generation data
- [x] Capacity data
- [x] Consumption data
- [x] Price data

**Comment by eldobbins** [comment]
There is a validator for frictionless data packages at https://create.frictionlessdata.io.  I uploaded `metadata.json` to it and it barfed at the license.  Am going to try and fix it.

**Comment by eldobbins** [comment]
My change to the license section passed the frictionless test. I approve of this format!  

I referenced this in the other issue and proposed a new structure for `data/`. If you like the new structure, can you shuffle the data into it and change the `path` to include a subdirectory. I intend this file to be the one that links all the different sections, though finishing `capacity` first is appropriate. We can make separate issues for the different sections.

**Comment by jikac** [comment]
I like it! We will want @ianalexmac to store his relevant CSVs here and add his metadata as well so I'll leave this open and rename accordingly.
