### ISSUE TITLE
Metadata parser for data downloads

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#39]
We would like to create a small script that parses the `metadata.json` file and produces a data dictionary as a CSV or something similar. This would allow us to put a download link for the data and another for the dictionary next to each other on the data portal page.

**Comment by ianalexmac** [comment]
Very basic metadata csv download option is up on the data page. I'm still not sure how to parse multiple levels of nested JSON or even what that would look like. At the moment I have the schema fields in table form, but I can't add keys "path" and "description without breaking things. Thoughts?

**Comment by ianalexmac** [comment]
I added the filepaths and descriptions to the quarto pages themselves. Maybe they don't ride along with the metadata download?

**Comment by ianalexmac** [comment]
Deployed to the data page
