### ISSUE TITLE
Add units to the metadata file

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#40]
We want to add some notation of units to the metadata.json file. 
- units should be machine readable, so we need a standard
- the standard should include the derived units we need to express
- the standard should be acceptable to tools/languages that will want to read the data
  - Python and R
  - collaborators like Catalyst

Because we need to balance all these things, I made an issue.

Things to look at:
- [UDUNITS2](https://docs.unidata.ucar.edu/udunits/current/#Database)
  - https://cran.r-project.org/web/packages/units/vignettes/measurement_units_in_R.html says works in R
     - " udunits on the other hand is the units standard of choice by the climate science community, and is adopted by the CF (Climate and Forecast) conventions, which mostly uses NetCDF" 
  - there are python language packages too
- [pint](https://pint.readthedocs.io/en/stable/getting/overview.html)
  - is python for sure but R = ??
  - used by Catalyst and Datacette. Well, [maybe](https://github.com/catalyst-cooperative/pudl/issues/1499)
- [UCUM](https://cran.r-project.org/web/packages/units/vignettes/measurement_units_in_R.html#udunits-versus-the-unified-code-for-units-of-measure-ucum) Unified Code for Units of Measure is maybe dead?
  - that R ref says "... links seem to be dead. UCUM is the preferred encoding for standards from the Open Geospatial Consortium"
- https://cf-xarray.readthedocs.io/en/latest/units.html extends pint to be like UDUNITS1
- [frictionless can't decide](https://github.com/frictionlessdata/specs/issues/216) and also [this](https://github.com/frictionlessdata/specs/issues/537)

**Comment by ianalexmac** [comment]
`"units":` have been added to `metadata.json`, which parse and show up on the table previews on the data page.

**Comment by eldobbins** [comment]
Closing this issue as complete. If we want to use a different standard later, we can switch.

PS. Added info from this card to the wiki to simplify coming back to it.

**Comment by jgunstone** [comment]
hi - 
is this addition shown anywhere in the documentation? I couldn't find units anyway... 
(not here: https://datapackage.org/recipes/metadata-in-table-schema/)

another units good standard: https://www.qudt.org/doc/DOC_VOCAB-UNITS.html

FYI in case its useful / interesting: 
the https://github.com/annotated-types/annotated-types?tab=readme-ov-file#unit package has an implementation that allows you to save units as metadata only; and then in the docs has a demonstrattion of a BYO units package implementation... thus side-stepping any authority on units or the units packages / standards that should be used....

**Comment by eldobbins** [comment]
@jgunstone we sorta added our own units based on a standard in R. Right, @ianalexmac?

I will add your ideas to https://github.com/acep-uaf/aetr-web-book-2024/wiki/Units where I was tracking info.

**Comment by ianalexmac** [comment]
That's right, we added units as a key:value pair to each column of data referenced in the metadata. In our case, we mostly just had currency (USD), MWh (megawatt-hour), and MW (megawatt). These units are pretty standardized in the energy field. I like the links you provided @jgunstone, but not sure it's in our best interest to switch from MWh to something like MegaW-HR. If our data had more complexity we might rethink this, but for now I think MWh is the most straightforward.

Many other columns were unitless, such as names of utility companies, regions, unique identifiers etc. These columns were written as NA.

Thanks for reaching out, we'll keep those links in mind going forward.

**Comment by jgunstone** [comment]
Hi - could you show where the key:value column data is so I could take a look? 

The uri is [MegaW-HR](https://qudt.org/vocab/unit/MegaW-HR) but in the link is a .ttl (and .json I think) which contains the UCUM code and other more common symbolic representations (i.e MWH, MW.hr). 

I do think there is something in the BYO approach... selecting a unit standard will be wrong for someone... (I built a package that uses [unyt](https://unyt.readthedocs.io/en/stable/) which I haven't seen reference here ...) but a string field that is defined as a unit that can be manipulated as your package sees fit has universal appeal. 

Thanks for your responses
