### ISSUE TITLE
Misc issues from proof reading

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#42]
- [x] Capacity: renewable totals are hardcoded. Liz added numbers from the draft but should that sum of renewables be replaced with R code?
- [x] figures justified oddly. Captions are centered but figures are left justified.
- [x] Consumption: after Figure 2 there is reference to a table that is not in the draft or in the web book.  Perhaps a place for @ianalexmac's data table magic?  Or maybe it should say "Figure" instead of "table"?  Assume the latter, but this should be checked.
- [x] The figure titles above the plots are too big. They look like section headers. Also they are redundant now that there are figure captions below.  Remove?
- [x] Figure margins are big on the top and small at the bottom. Which makes the text look like it belongs to the wrong figure. Either move the text below each figure or change the margins (css)
- [x] Consumption: not sure where to put the note about the "other" category. Should it really be with every single figure?  Footnote is maybe not enough emphasis.  
- [x] Consumption: rural remote numbers are slightly different between the draft and the calculated numbers in the web book. It's a very slight difference but the coastal and rail belt numbers are exactly the same so it's weird
- [x] prices: cannot proof the beginning of the prices page because it is so different from the draft
- [x] prices: railbelt prices and percentage changes are different between the draft and the web book. book prices match the figure so maybe draft is wrong.
- [x] prices: CSS fix for figure margin reduction made the dropdown on the raincloud plot inaccessible

**Comment by ianalexmac** [comment]
On Capacity page:
`echo: false` was called in each block, but one block didn't have the call (FileAttachment() moved to fix bug)
moved to `echo: false` to page-level yaml chunk

**Comment by eldobbins** [comment]
Moved figure captions above the plots, and replaced the coded titles and header with those.

**Comment by eldobbins** [comment]
> Note that [the image] cannot be centered if the width is set to 100% (full-width).

According to https://www.w3schools.com/howto/howto_css_image_center.asp.  So look in browser inspector to see what the width is. For `ojs` figures, it is

``` 
.quarto-figure>figure {
width: 100%;
margin-bottom: 0;
}
```
I tried changing that width in `style.css`, `_quarto.yml`, and in the header of the file but nothing sticks.

On the other hand https://observablehq.com/plot/features/plots#layout-options says "On Observable, the width can be set to the [standard width](https://github.com/observablehq/stdlib/blob/main/README.md#width) to make responsive plots" which means that the figures resize as the window size changes (i.e. for mobile devices etc)

Adding `width: Math.max(width, 550),` to the `Plot.plot` in the `ojs` code block did center the figure, but the legend stayed on the left which looked dumb.

So maybe figures must be 100% to be responsive, but being 100% requires them to be left justified. So we are at an impasse.  Copied this comment to the [AETR wiki](https://github.com/acep-uaf/aetr-web-book-2024/wiki/Data-Visualization-with-Observable-JS).

**Comment by ianalexmac** [comment]
> prices: railbelt prices and percentage changes are different between the draft and the web book. book prices match the figure so maybe draft is wrong.

Thanks for catching this. The difference is due to a change in numerical rounding. The web book is more accurate, I'll update the draft to match.

**Comment by jikac** [comment]
> Consumption: after Figure 2 there is reference to a table that is not in the draft or in the web book. Perhaps a place for @ianalexmac's data table magic? Or maybe it should say "Figure" instead of "table"? Assume the latter, but this should be checked.

The reference to a table after Figure 2 on the Consumption page in AETR Google Doc was just a mistake. It was supposed to say figure. I've checked that one off.

**Comment by jikac** [comment]
> Capacity: renewable totals are hardcoded. Liz added numbers from the draft but should that sum of renewables be replaced with R code?

Fixed with https://github.com/acep-uaf/aetr-web-book-2024/commit/62a10cd435c5d91dba59a8a9514de60d6a279680

**Comment by jikac** [comment]
>  Figure margins are big on the top and small at the bottom. Which makes the text look like it belongs to the wrong figure. Either move the text below each figure or change the margins (css)

I've discovered that the issues with spacing have to due with wrapping the blocks as figures. Fixed by adding the following custom CSS,

```
.quarto-figure {
  margin-top: -3em;
}
```

RE: https://github.com/acep-uaf/aetr-web-book-2024/commit/559e160b04cad8b2e0999944149095986efef294

**Comment by jikac** [comment]
> figures justified oddly. Captions are centered but figures are left justified.

Fixed by adding the option `width: width` to every plot. Tells Observable JS to make the width of the chart equal to the width of the display block.

**Comment by jikac** [comment]
> prices: CSS fix for figure margin reduction made the dropdown on the raincloud plot inaccessible

Fixed in https://github.com/acep-uaf/aetr-web-book-2024/commit/05fa09775e20a57a6614ae50856e9efb5c08104c by creating a custom CSS class for the raincloud plot that undoes the caption spacing fix in https://github.com/acep-uaf/aetr-web-book-2024/commit/559e160b04cad8b2e0999944149095986efef294

**Comment by jikac** [comment]
>  Consumption: not sure where to put the note about the "other" category. Should it really be with every single figure? Footnote is maybe not enough emphasis.

My solution to this was to include bullets in the first paragraph that define the customer classes.

**Comment by jikac** [comment]
> Consumption: rural remote numbers are slightly different between the draft and the calculated numbers in the web book. It's a very slight difference but the coastal and rail belt numbers are exactly the same so it's weird

There seems to be a difference in the data that R is spitting out in comparison to the stuff that Python spit out but only for this region. I'm going back through my steps to diagnose.

**Comment by jikac** [comment]
I have found that the data being used in the web version of this report is more up to date than the one that I was using in the Google Doc. In particular, I found differences in the 2016 and 2019 Rural and Remote region data where more data has now been added. This is why in every case the differences were higher in the web book version.
