### ISSUE TITLE
Add "How to Cite"

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#48]
### Dayne suggests:

> We should add a "how to cite this web book" on the Credits page with a recommended citation method on the Credits page where people might look for this. Just taking a stab at it following the APA website style using the following style

> Name of Group. (YYYY, Month Day). *Title of work*. Site Name. https://xxxxxx/
My first draft recommendation is this:

> Alaska Center for Energy and Power (2024, Apr. 15) 2024 *Alaska Energy Trends Report Web book*, aetr-web-book-2024. https://acep-uaf.github.io/aetr-web-book-2024

### Liz's points
- "Electricity" not "Energy"
- should be a `_citation.qmd` file and also equivalent `.md` in the repo that echos that (What's the repo standard)
- Think about adopting some journal's standard syntax and not a random one.

#### Chicago Manual of Style
Examples from https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html#cg-website
```
Bouman, Katie. “How to Take a Picture of a Black Hole.” Filmed November 2016 at TEDxBeaconStreet, Brookline, MA. Video, 12:51. https://www.ted.com/talks/katie_bouman_what_does_a_black_hole_look_like.

Google. “Privacy Policy.” Privacy & Terms. Last modified April 17, 2017. https://www.google.com/policies/privacy/.

Yale University. “About Yale: Yale Facts.” Accessed May 1, 2017. https://www.yale.edu/about-yale/yale-facts.
```

**Comment by ianalexmac** [comment]
https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-citations

**Comment by ianalexmac** [comment]
Options for location include:

* Before executive summary
* In every sidebar

**Comment by jikac** [comment]
I like the idea of providing a downloadable citation as well for people using bibliography files. This would require us to have a prefilled template and the download button would need to update the "accessed on" field for citations. I've drafted up some of the most common citation formats (BibTeX, BibLaTeX, and RIS). We can always add a DOI field later.

**BibTeX**
```
@misc{aetr_web_book_2024,
    author = {{Alaska Center for Energy and Power}},
    title = {{2024 Alaska Electricity Trends Report}},
    year = 2024,
    url = {https://acep-uaf.github.io/aetr-web-book-2024/},
    note = {Accessed on April 16, 2024}
}
```

**BibLaTeX**
```
@online{aetr_web_book_2024,
    author = {{Alaska Center for Energy and Power}},
    title = {{2024 Alaska Electricity Trends Report}},
    year = 2024,
    url = {https://acep-uaf.github.io/aetr-web-book-2024/},
    urldate = {2024-04-16}
}
```

**RIS**
```
TY  - MISC
AU  - Alaska Center for Energy and Power
TI  - 2024 Alaska Electricity Trends Report
PY  - 2024
DA  - 2024
UR  - https://acep-uaf.github.io/aetr-web-book-2024/
N1  - Accessed on April 16, 2024
```

**Comment by jikac** [comment]
Connecting commit to this issue 5d90f943ee316150ac42fc816707f6b575099448. Note that is commit does not include dynamic URL access dates for the downloadable citations.

**Comment by ianalexmac** [comment]
Rough draft of citations is up on the site. Dynamic "Accessed on *today's date*" script written for the markdown citation. 

Dynamic citations in the downloadable citations are a little trickier. We're asking the frontend to write to file, something that we've had issues with in the past. I'm not sure about feasibility. We could fake it by writing the dynamic date in the filename when downloaded.

**Comment by eldobbins** [comment]
I don't think we are there yet.  I like the dynamic date in index.qmd, but the files are not updated (as Ian said)

Just came across https://quarto.org/docs/authoring/create-citeable-articles.html#web-articles which seems to describe a better way.

**Comment by jikac** [comment]
This seems ideal.

**Comment by eldobbins** [comment]
I am trying it. I cannot get it to work.  I'm going to try it in my website sandbox.

**Comment by ianalexmac** [comment]
We have another option: The plain text citation could remain as-is. The .bib and .bibtex files could be built from scratch when the user clicks "download", which would give us a chance to stamp the current date within the file. This would prevent us from messing with frontend/backend separation. I'm pretty sure I can work this all up with a little javascript.

**Comment by ianalexmac** [comment]
Ok! Download buttons are up! Date auto-generates and inserts into the file. This is still a rough draft, but let me know what you think.

**Comment by eldobbins** [comment]
Thank goodness you got it.  Using [Create Citable Articles](https://quarto.org/docs/authoring/create-citeable-articles.html#web-articles) was a triple failure

1. it works on websites but the same code added to the same place does nothing in a book
2. adding `citation:true` to `_quarto.yml` (website) adds a citation to every page but uses the title of the page, not the title of the book
3. adding citation info to `index.qmd` worked, but look at the author!  It thought "Alaska" was a first name...

code added to the header (front matter)
 ```
author:
  - name: "Alaska Center for Energy and Power"
    url: https://www.uaf.edu/acep/
citation: true
```

added this to the bottom of the page (div id="quarto-appendix")
<img width="983" alt="image" src="https://github.com/acep-uaf/aetr-web-book-2024/assets/30326065/8658a59d-c23a-42df-801f-3ead4d8f57ac">

**Comment by ianalexmac** [comment]
@jikaczmarski @eldobbins Could you double check the citation downloads are in the right format and readable? I've never interacted with .bib or .bibtex or .ris files. Just want to double check that everything turned out well.

**Comment by eldobbins** [comment]
Based on stuff I put in wiki, these changes are planned.

1. remove the code that generates the .bibtex file.  Keep the .bib and .ris file
2. change the RIS type (TY) to ~~WEB~~ `ELEC` (Zotero chose `ELEC`, EndNote uses `WEB`)
3. the date in the .bib file (`urldate`) needs to be `YYYY-MM-DD` and use the current date not the publish or modification date. 
4. (remove the `citations` directory)

After these changes are made, I will load these files into Zotero to make sure they work

**Comment by eldobbins** [comment]
I made the changes. 
- Citation on the website matches Chicago Manual of Style
- BibLaTeX file loads great in Zotero and in Overleaf. 
- RIS file loads into Zotero fine. Date goes into `date` field and not `accessed` field which isn't great but I can live with it.
