### ISSUE TITLE
Legend/Tooltip for energy region leaflet

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#50]
It would be ideal to have legend or some sort of tooltip for the leaflet that displays AEA/ACEP energy regions. Right now the regions light up with different colors but there is no way to see what they are called.

**Comment by ianalexmac** [comment]
Regional tooltips added to map. Funky box pops up when clicked, not sure how to prevent. 

Also, we would love to have community points on the map. Stay tuned.

**Comment by ianalexmac** [comment]
> Regional tooltips added to map. *Funky box pops up when clicked, not sure how to prevent.*

Solved! The funky box was a CSS issue, added to styles.css: `path.leaflet-interactive{outline: none;}`
