### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#58]

**Comment by ianalexmac** [comment]
Server analytics? Like web traffic and such? 

At the moment, GH Pages doesn't provide access to traffic data. The repository itself has traffic data available ([see documentation here](https://docs.github.com/en/repositories/viewing-activity-and-data-for-your-repository/viewing-traffic-to-a-repository)), but this is NOT the GH Page data that most folks are looking for.

There does seem to be [strong community interest](https://github.com/orgs/community/discussions/31474) in the feature. Presumably this is on the horizon (GH has all the server log data, just a matter of access), but nothing yet. 

The nuclear option: Set up [Google Analytics](https://marketingplatform.google.com/about/analytics/) or some other enterprise-level solution. Note: privacy concerns, expensive, heavy-handed. Not recommended.

**Comment by eldobbins** [comment]
@ianalexmac did we get any info from the QR code?

Another options is https://matomo.org/ = "powerful web analytics platform that gives you 100% data ownership".  The old AEDG used the precursor to that system.

**Comment by eldobbins** [comment]
Thinking we should close this issue. 

I am disinclined to use Google analytics because of the overhead involved. And Dayne was talking about hosting AETR on the Data Gateway (AEDG) which will likely have analytics so I'm hoping this problem will solve itself.
