### ISSUE TITLE
Finish methods page

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#7]

**Comment by eldobbins** [comment]
@jikaczmarski @ianalexmac could you please check the methods section.  I think it is almost done.

Outstanding issues
- Jesse's markdown he sent includes "PH (?) Assessments".  What is that?  Should it be removed?
- Sara has a comment in the original doc "What is an individual electric authority?  SEAPA?"  Can we address that?

**Comment by ianalexmac** [comment]
I updated prose about PCE this morning. We are very close.

Is "PH Assessments" a reference to solar?

**Comment by jikac** [comment]
@ianalexmac @eldobbins Fixed but using the updated language in the AETR Google doc. As for the individual electric utility sources, we really would be hard pressed to name them individually. SEAPA is one of them, but we don't know the extent that they were involved in the data. Neil just sometimes lists utilities as a data source.
