### ISSUE TITLE
Verify that scripts directory is now unneeded and delete it.

### ISSUE THREAD

**Issue by eldobbins** [acep-uaf/aetr-web-book-2024#70]
In reference to #69 which moves the action to `data/`:  The patches in `data/` and `data/main.R` may render things in `scripts/` like `scripts/main.R` obsolete.  There needs to be some picking through to make sure we don't lose anything important if we do delete scripts that are no longer relevant.

Optional twists:
- instead of deleting deprecated scripts, they could be moved to a subdirectory
- instead of having data processing scripts in `data/`, they could be transferred to `scripts/` when that directory is polished.

(The justification for separating scripts and data is that scripts can be tracked in GitHub, but data really shouldn't. If they are separate, then `data/` can be listed in `.gitignore` while `scripts/` is tracked normally. Not really an issue with our tiny dataset - thinking of the future.)

**Comment by jikac** [comment]
One major dependency is the `scripts/inline_functions` folder. This contains functions written in R for calling statistics in text. We just need to maintain this somewhere as it's pretty important. It can move with fairly limited refactoring elsewhere.

**Comment by ianalexmac** [comment]
Please don't delete `scripts/` it contains code vital to the build.

**Comment by eldobbins** [comment]
This is an enhancement that is being obsoleted by all the other ways we are generating data to support reports in the future. Will close without working on it.
