### ISSUE TITLE
Citation download buttons have broken

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#74]
Somewhere in the last few PRs the citation download button on the introduction page has broken.

**Comment by ianalexmac** [comment]
There was a deliberate effort to move the download buttons in order to render the PDF without breaking things. Since then, we have learned a few more tricks for conditional rendering, so the buttons could be brought back to the introduction page without breaking the PDF. Thoughts @eldobbins ?

**Comment by jikac** [comment]
I'm okay with removing the buttons if that's the intention. That being said, it doesn't appear that ojs is rendering the current date.

**Comment by ianalexmac** [comment]
I think removing buttons on the intro page was done out of necessity rather than desire. Since we now have tools that allow us to put buttons on the front page, I propose that we put them back.
