### ISSUE TITLE
Fix formatting in Historical Reports (PDF version)

### ISSUE THREAD

**Issue by ianalexmac** [acep-uaf/aetr-web-book-2024#81]
We've got some formatting issues on the Historical Reports portion of the PDF. I believe the fix involves modifying TEX files. Probably a pain and not high priority, but worth discussing anyways.

Screenshot of the problem:

![historical_reports](https://github.com/user-attachments/assets/d2800cc1-3a17-43e2-8c9f-ce864c2b324a)

**Comment by jikac** [comment]
Yea, this is going to be a result of Quarto's table package implementations. LaTeX table implementation is really bad using basic packages and I always recommend things like [tabularx](https://texdoc.org/serve/tabularx.pdf/0) over tabular. However, I'm not sure we can override Quarto's default tabular environment.

My intuition leads me to two options,
1. Remove the table from the PDF render
2. I create the entire table using a `\tabularx` implementation and we call that conditionally if a PDF is being rendered.

@ianalexmac Do you fell like we might be able to conditionally call a `.tex`?

**Comment by ianalexmac** [comment]
@jikaczmarski I remember you saying that tables in LaTeX are notoriously bad. Bummer. However I'm pretty sure I have a trick to conditionally call a `.tex` file depending on the render format.

**Comment by eldobbins** [comment]
Fixed text overwriting, but could not make other stylistic improvements (shading, borders, padding) that would improve readability.

**Comment by eldobbins** [comment]
Eh.  It looks OK.  Even Jesse says so.
