### ISSUE TITLE
Fix figure titles in PDF

### ISSUE THREAD

**Issue by emr65df** [acep-uaf/aetr-web-book-2024#83]
Consumption & Sales: Currently the plot titles do not contain a figure number

- [x] add figure number in the plot titles including the chapter and order of appearance of the figure, `ex. Figure 3.2:`

Prices: some plot titles do not contain a figure number, or some plot titles contain a figure number by order of appearance but not the chapter number

- [x] add figure number in the plot titles that include the chapter and order of appearance number, ex `Figure 4.2`

I can QA/QC once complete.

**Comment by ianalexmac** [comment]
Some of this may have been solved by the recent PR. Confirm by looking at the PDF here: https://github.com/acep-uaf/aetr-web-book-2024/blob/gh-pages/2024-Alaska-Electricity-Trends-Report.pdf

**Comment by emr65df** [comment]
Resolved.
