### ISSUE TITLE
Complete the price page

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#9]

**Comment by ianalexmac** [comment]
Raincloud plots added, as well as data point tips for exploring which town corresponds to the selected (hovered) dot.

**Comment by ianalexmac** [comment]
- [x] adjust color palette of raincloud plots
- [x] remove y axis label on raincloud
- [x] revamp regional prose
- [x] add labels/legends for temporal graphs

**Comment by ianalexmac** [comment]
The price page is done for now, I'm transitioning to writing inline functions.
