### ISSUE TITLE
Barlow font broken?

### ISSUE THREAD

**Issue by ianalexmac** [acep-uaf/aetr-web-book-2024#94]

**Comment by eldobbins** [comment]
There is this site for testing: https://fonts.google.com/specimen/Barlow?preview.text=Alaska%20Center%20for%20Energy%20and%20Power

It doesn't look the same as what is in the PDF. An example: The capitol C is round in ours and has a straight back in the official page. Also the lower case f should be scrunched upward but ours is more symmetric.

Another reference: https://www.uaf.edu/universityrelations/guidelines/design/fonts.php which also has Barlow with a flat-backed C and scrunched up f.

**Comment by eldobbins** [comment]
This is Barlow in Font Book on my Mac: 
<img width="780" alt="image" src="https://github.com/user-attachments/assets/a15dc241-7a76-4617-b7e3-1eb8bcf956e6">

But the PDF my Mac renders locally has the same font as the one rendered and posted in GitHub. So it isn't working in either space.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/0e0142e0-2976-4af1-81fc-3ffd113153a0">

**Comment by eldobbins** [comment]
https://www.myfonts.com/pages/whatthefont - results inconclusive.

`% strings 2024-Alaska-Electricity-Trends-Report.pdf | grep -I FontName` = nothing

Foxit Pro says:
<img width="788" alt="image" src="https://github.com/user-attachments/assets/b4dacb87-102a-42fe-bd94-0064aefb2342">

**Comment by eldobbins** [comment]
My guess is it is Latin Modern Sans: https://tug.org/FontCatalogue/latinmodernsans/

So it is reverting to a LaTeX default font?  But I could not get the PDF to render without installing the Barlow font so it thinks it is doing one thing but subbing in something else later?

@jikaczmarski can you check my reasoning?
