### ISSUE TITLE
Add UA publishing requirements

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#95]
Non discrimination langauge

**Comment by eldobbins** [comment]
Notice on page 3 of PDF has non discrimination language.  Needs to be ported into the HTML.

Doing that now on my fork. Soon there will be a PR.

**Comment by eldobbins** [comment]
Emilia just sent this:

> I took a peek at the [acep-uaf.github.io](http://acep-uaf.github.io/) page and noticed that it doesn't have [UAF's statement of nondiscrimination](https://www.alaska.edu/nondiscrimination/). According to this website, the shortened version should be included on university websites. Would be good to include for compliance! I don't know what the threshold for something becoming a university website, but I would think that anything that mentions UAF might count?

So where I put it is not good enough because she did not see it.  Microstatement in the footer?
