### ISSUE TITLE
Review CReDiT

### ISSUE THREAD

**Issue by jikac** [acep-uaf/aetr-web-book-2024#96]
Make sure updates are made to credit author statements.

**Comment by eldobbins** [comment]
Updating now

- all citation formats (BibTex, RIS, CREDIT, etc)
- both HTML and PDF

Will send for comments when complete

**Comment by eldobbins** [comment]
Request for comments was sent but lots of people are out for Labor Day so we might not get much response.  Changes were made to address the comments I did receive.


- [x] Jesse
- [x] Ian
- [x] Steve: said "looks good"
- [x] Neil: corrections to DOWL
- [x] Dayne: credit hist report figure, reformat table
- [ ] Gwen
- [x] Shivani: her last name is Bhagat
- [x] Emily: "is accurate"
- [ ] Erika
- [x] Sara: ok'd 9/4
- [x] Brittany:  "looks ok" on 9/4

9/4 Update: nudged holdouts (Sara, Brittany, Gwen, and Erika) again

**Comment by jikac** [comment]
@eldobbins Hey Liz, are we all good to close this issue?

**Comment by eldobbins** [comment]
Erika left without care.
Gwen withheld approval. She asked to have "funding acquisition" removed from her CRediT roll-call. 

Making final edit to publish.
